# Generated automatically from Makefile.in by configure.
#
# File:		Makefile.in
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for controls example (UNIX).

top_srcdir = ../..
top_builddir = ../..
program_dir = samples/caps07-02-2005Multiplateforme

PROGRAM=caps

OBJECTS =	Adminstration.o \
		broadcast.o \
		Agree.o \
		ChatText.o \
		Connexion_client.o \
		connexion.o \
		create_account.o \
		crypto.o \
		Download.o \
		engine.o \
		ExplorerClient.o \
		ExplorerServer.o \
		FileInfo.o \
		FileList.o \
		MyApp.o \
		MyFrame.o \
		MyPanel.o \
		NewsGroup.o \
		Options.o \
		Panel_PrivChat.o \
		Panel_PublicChat.o \
		Panel_Transfert.o \
		PopupCreate.o \
		preview.o \
		Rep.o \
		ServData.o \
		User.o \
		Utilisateur.o

DEPFILES=$(PROGRAM).d

include ../../src/makeprog.env

-include $(DEPFILES)
