void	receive_user_info(t_transac *transac);
void main_bridge();
void    completion();
void    receive_login_list(t_transac *transac);
void	show_user_access(char *access, int j);
char	*c_to_b(unsigned char ti);
char     *func_commands(int connfd);
char    *get_command(char *str);
void	receive_type_string(char *name, int len);
void	receive_error(t_transac *transac);
void    receive_download(t_transac *);
void    receive_upload(t_transac *);
void    receive_get_user(t_transac *);
void	receive_chat(t_transac *);
void	receive_login(t_transac *);
void	receive_agreement(t_transac *);
void	receive_user_list(t_transac *);
void    receive_user_access(t_transac *);
void    receive_file_list(t_transac *);
void    receive_server_msg(t_transac *);
void	receive_broadcast(t_transac *transac);
void	receive_delete_user(t_transac *);
void	receive_file_info(t_transac *transac);
